### ISSUE TITLE
cargo build is broken

### ISSUE THREAD

**Issue by olekspickle** [stiiifff/substrate-deps#24]
For some reason `cargo install substrate-deps` failed to build.

<details>
<summary>Error</summary>

![Screenshot_20200311_152854](https://user-images.githubusercontent.com/22867443/76421951-22a5ba80-63ad-11ea-9151-ca521dbff65e.png)

</details>

Built from source working as charm though. I am sure it is some cargo-deps version mismatch somewhere.

**Comment by stiiifff** [comment]
Thanks for reporting this ! Could you give another shot w/ latest v0.2 release, it should be solved.
